### ISSUE TITLE
How to provide Unique Key to a Job?

### ISSUE THREAD

**Issue by marcelinhov2** [lykmapipo/kue-scheduler#106]
At the docs, you make mention of define an unique key for a Job, but I can not do it and idk why. =/

**Comment by masitko** [comment]
Just add unique method with name of the job like in the example:
`var job = Queue
            .createJob('unique_every', { timezone: 'Europe/Amsterdam' })
            .priority('normal')
            .unique('unique_every');
`

**Comment by lykmapipo** [comment]
@marcelinhov2 

@masitko point it out clearly. You should use `.unique(<tag|unique value>);` to provide unique key to a job.

Please ensure its `unique` across your `clusters` or `deployment instances` to support concurrent `workers`.

Thanks.
