### ISSUE TITLE
Cancel a scheduled job

### ISSUE THREAD

**Issue by arvindr21** [lykmapipo/kue-scheduler#12]
Hello,

Thanks for the scheduler. Wanted to know, if there is an API to cancel a scheduled job.

Thanks.

**Comment by lykmapipo** [comment]
@arvindr21 

Current I have not implement it yet.
Am open to discussion.

**Comment by Roam-Cooper** [comment]
Updating a scheduled job, too. We wanted to be able to update the frequency that a job runs sometimes.

**Comment by lykmapipo** [comment]
@arvindr21 

- For `delay` and `now` jobs you can use [remove](https://github.com/Automattic/kue#job-cleanup)
- For every job am working on it.

**Comment by lykmapipo** [comment]
@arvindr21 

[Implemented](https://github.com/lykmapipo/kue-scheduler#removeidjobcriteria-done) in [v0.4.0](https://github.com/lykmapipo/kue-scheduler/releases/tag/v0.4.0)
