### ISSUE TITLE
Package on npm source is not updated

### ISSUE THREAD

**Issue by elwhizard** [lykmapipo/kue-scheduler#123]
When installing package from npm, the source code is not updated. I've noticed this when I made jobs with timezone config did not work. I've checked the installed package and this commit [c55574306](https://github.com/lykmapipo/kue-scheduler/pull/114/commits/c55574306bf917f6f83bb96e9f2176f2a89c4ced) merged from PR #114 isn't reflected.

Currently using this github repo as package source to make timezone work and up to date with latest version.

**Comment by lykmapipo** [comment]
@elwhizard Latest version published
