### ISSUE TITLE
Usage with Typescript does not work for unique jobs

### ISSUE THREAD

**Issue by heniotierra** [lykmapipo/kue-scheduler#128]
I am using this lib along with Typescript, but if I try the example to create a unique Job instance, I get the following message from ts compiler:

    The property 'unique' does not exist in type 'Job'.

This is the code:

```
      var options = {
        prefix: 'w',
        redis: {
          port: +process.env.KUE_REDIS_PORT,
          host: process.env.KUE_REDIS_HOST,
          db: process.env.KUE_REDIS_DB
        },
        restore: true
      };

      const Queue = kue.createQueue(options);

      const job = Queue
        .createJob('unique-every', null)
        .attempts(attempts)
        .backoff({
          delay: backoff,
          type: 'fixed'
        })
        .priority('normal')
        .unique('unique-every');

      Queue.every('5 seconds', job);

      Queue.process('queue-control', this.viabilityTasks.viabilityComputationQueueControl);
```

How can I get this to work?

Thanks,

**Comment by lykmapipo** [comment]
@heniotierra May be it missing from [type definition](https://github.com/lykmapipo/kue-scheduler/blob/master/index.d.ts). I will appreciate PR for the fix.

**Comment by heniotierra** [comment]
@lykmapipo  I have fixed it, but it required a patch to https://github.com/lykmapipo/kue-unique as well. Will send the PRs.

**Comment by heniotierra** [comment]
These are the PRs:
https://github.com/lykmapipo/kue-scheduler/pull/129
https://github.com/lykmapipo/kue-unique/pull/11

**Comment by lykmapipo** [comment]
@heniotierra On it.
