### ISSUE TITLE
Lodash dependency missing

### ISSUE THREAD

**Issue by KeKs0r** [lykmapipo/kue-scheduler#15]
Hi,

wanted to use this library, but I am using a old version of lodash which does not include snakeCase for "unique".

I checked package.json and it is only defined as devDependency, maybe it makes sense to define lodash as real dependency. (probably better than peerdependency, due to the version mixmatch. Or if only a few  functions from lodash are used, maybe directly the ones that are needed.

**Comment by lykmapipo** [comment]
@KeKs0r 

I have put directions on the [Installation](https://github.com/lykmapipo/kue-scheduler#installation). 

I found it be a good options to install lodash separately. Am open for further discussion

**Comment by KeKs0r** [comment]
okay, so i kinda overlooked this step, but also your documentation does not specify which lodash version (I had lodash installed, just not the version this plugin needed).

So the minimum what should be done is document which minimum versions are needed. But I also would say, that this is the exact same thing the package.json is for. For me the questions is rather if it makes more sense to define lodash as dependency or peerDependency

**Comment by lykmapipo** [comment]
@KeKs0r 

I think we can go with defining `dependencies` directly.
How is that?. If so I will appreciate a PR.

:+1:

**Comment by KeKs0r** [comment]
Pr open in #16

**Comment by KeKs0r** [comment]
solved with #16
