### ISSUE TITLE
Deleting job on shedule success results in crash

### ISSUE THREAD

**Issue by IvanMMM** [lykmapipo/kue-scheduler#20]
>VK-0 (err): TypeError: Cannot set property 'alreadyExist' of undefined
>VK-0 (err):     at /home/badvolt/VK/node_modules/kue-scheduler/node_modules/kue-unique/index.js:196:42
>VK-0 (err):     at /home/badvolt/VK/node_modules/kue/lib/queue/job.js:169:14
>VK-0 (err):     at try_callback (/home/badvolt/VK/node_modules/kue/node_modules/redis/index.js:592:9)
>VK-0 (err):     at RedisClient.return_reply (/home/badvolt/VK/node_modules/kue/node_modules/redis/index.js:685:13)
>VK-0 (err):     at ReplyParser.<anonymous> (/home/badvolt/VK/node_modules/kue/node_modules/redis/index.js:321:14)
>VK-0 (err):     at ReplyParser.emit (events.js:107:17)
>VK-0 (err):     at ReplyParser.send_reply (/home/badvolt/VK/node_modules/kue/node_modules/redis/lib/parser/javascript.js:300:10)
>VK-0 (err):     at ReplyParser.execute (/home/badvolt/VK/node_modules/kue/node_modules/redis/lib/parser/javascript.js:211:22)
>VK-0 (err):     at RedisClient.on_data (/home/badvolt/VK/node_modules/kue/node_modules/redis/index.js:547:27)
>VK-0 (err):     at Socket.<anonymous> (/home/badvolt/VK/node_modules/kue/node_modules/redis/index.js:102:14)
>VK-0 (err):     at Socket.emit (events.js:107:17)
>VK-0 (err):     at readableAddChunk (_stream_readable.js:163:16)
>VK-0 (err):     at Socket.Readable.push (_stream_readable.js:126:10)
>VK-0 (err):     at TCP.onread (net.js:538:20)

This is my function:

    queue.on('schedule success', function(job) {
        job.remove(function(err){
            if (err) console.error('Cannot remove scheduled job #'+job.id);
            //console.log('removed scheduled job #%d', job.id);
        });
    });

And I call callback() like this:

        async.waterfall([
            getRandomToken, 
            getProjectsTargets,
            preformExecuteRequest
        ],function(err,result){
            if(err) return done(err);
            return done();
        })

**Comment by lykmapipo** [comment]
@IvanMMM 

Please try to use v0.4.1
