### ISSUE TITLE
Retrieving jobExpiryKey and jobDataKey when scheduling a job

### ISSUE THREAD

**Issue by hfreire** [lykmapipo/kue-scheduler#26]
Hi!

Quick question: How is one supposed to retrieve jobExpiryKey and jobDataKey when scheduling a job? 

Long question: According to the documentation in order to remove a job one could use the remove API with a criteria that contains the jobExpiryKey, jobDataKey or the unique identifier. But how is one supposed to retrieve those keys (jobExpiryKey, jobDataKey) if he intends to remove a scheduled job later on?

**Comment by lykmapipo** [comment]
@hfreire 

You may just pass a job instance and will figure out.
