### ISSUE TITLE
extend options from kue

### ISSUE THREAD

**Issue by vikrantpogula** [lykmapipo/kue-scheduler#27]
I've tried a couple of configurations to get the options from Kue singleton.

The following works 
```
import kue from 'kue-scheduler';
var queue = kue.createQueue({
  prefix: `defaultQueue`
});
```

but the following doesn't

```
import kue from 'kue-scheduler';
var queue = kue.createQueue({
  prefix: `defaultQueue`,
  redis: {
    db: 7, // if provided select a non-default redis db
  }
});
```

Any help on what I might be doing wrong would be appreciated.

**Comment by lykmapipo** [comment]
@vikrantpogula 

Just know only one kue singleton exist per process so if you try to create it multiple times
only the first instance will be returned.

Cross check if there is any part of your codes instantiate kue with default options.

Also I will cross check with `kue-scheduler` if it fails to merge the options.

**Comment by lykmapipo** [comment]
@vikrantpogula 

[See](https://github.com/lykmapipo/kue-scheduler/blob/master/test/instatiation.spec.js#L17).

Hope it will help.
