### ISSUE TITLE
Redis pubsub filter

### ISSUE THREAD

**Issue by keenondrums** [lykmapipo/kue-scheduler#4]
Redis can send different kind of messages through pubsub. Right now kue-scheduler upon receiving incorrect mesage. We gotta filter messages to proccess only kue related ones.

fix:

/**
 * filter not related to kue messages
 *
 * @param jobExpKey
 */
function filterBazar(jobExpKey) {
    return jobExpKey.match(new RegExp('^' + kue.singleton._options.prefix + ':'));
}

.....

Queue.prototype._subscribe = function () {
    //this refer to kue Queue instance context
    var self = this;

    //listen for job key expiry
    this
        ._listener
        .on('message', function (channel, jobExpiryKey) {

            if (!filterBazar(jobExpiryKey)) {
                return;
            }

            async
                .waterfall(
                [ .....

**Comment by lykmapipo** [comment]
@keenondrums 

I will appreciate to have a pull request for this.

**Comment by keenondrums** [comment]
My pleasure.

**Comment by lykmapipo** [comment]
@keenondrums 

Fixed by [merge your pull request](https://github.com/keenondrums/kue-scheduler/commit/457d4c6d67c22cc55f19a61394f9b46a60a72d76) and [what i had](https://github.com/lykmapipo/kue-scheduler/commit/5942a552c006508a2f69f222025b84af9e72ac75).

Thanks.
