### ISSUE TITLE
Resuming from missed schedule

### ISSUE THREAD

**Issue by Konkrad** [lykmapipo/kue-scheduler#44]
Currently it doesn't look like kue-scheduler resumes from an schedule which is already over. For me the desired behavior would be that this event fires when the first client connects and a new interval gets set.

``` js
//create.js
var kue = require('kue-scheduler');
var Queue = kue.createQueue();
var data = {ms: "Lorem Ipsum"}
var job = Queue
            .createJob('test', data)
            .unique('test')
Queue.every('30 seconds', job)
```

``` js
//process.js
var kue = require('kue-scheduler');
var Queue = kue.createQueue();

Queue.process('test', function(job, done) {
    console.log(`${job.id} - ${new Date().toLocaleTimeString()} - ${job.data.ms}`)
    done();
});
```

When I start `create.js`, kill it after it created the job and start `process.js` within 30 seconds everything works well. If starting `process.js` after the 30 seconds nothing happens.

**Comment by gmcnaught** [comment]
This is because redis pubsub does not replay if a pubsub message is missed. 

I'm actually working on a function to check all kue schedules in redis and reschedule any missed right now - I can send in a PR when I get that working.

**Comment by lykmapipo** [comment]
Hello,

As of now kue-scheduler doesn't have a mechanism to re-fire key that have
already expiry as it relies on redis key expiry events.

So if you schedule and cancel for a time larger than your schedule time
then you will miss the job in your process worker.

**Comment by marshauf** [comment]
Is it possible to remove the job descriptions from redis but keep running jobs and recreate the jobs?
Do the recreated jobs use the existing job instances?

**Comment by fruch** [comment]
Looks like i'm hitting this when I'm trying to test redis connectivity
i.e. when I'm disconnecting from redis while the schdule should worked, and reconnecting it.

can you provide some example on how to to recover from redis disconnect.
do we need to recreate the jobs ? or what exactly ?

**Comment by lykmapipo** [comment]
@gmcnaught should be a separate function that can be called explicitly but also we will pollute the options to allow `auto-reschedule`.

@gmcnaught can we work on this together. I will appreciate.

**Comment by fruch** [comment]
@lykmapipo 
I was able to solve it for my use case (I.e. couple of unique jobs), by connecting the redis 'ready' signal, and recreating the jobs. it would be nice if kue-schedule would emit a ready signal, so you can apply your logic. (Like I did, or re-instate the non-unique jobs), anyhow handling disconnects clearly is a must for a scheduler. 

I'll try to send my example next week when I'll be back from vacation. (My wife banned bringing my laptop...)

I thanks for the quick responses.

**Comment by lykmapipo** [comment]
@fruch I will appreciate the hook.

Thanks.

**Comment by fruch** [comment]
see #63 for my example.
