### ISSUE TITLE
should be able to restore schedules when restarted

### ISSUE THREAD

**Issue by lykmapipo** [lykmapipo/kue-scheduler#51]
1. should persist schedules on shutdown
2. should restore schedules on restart

**Comment by sunkuo** [comment]
Sir, I had reviewed your code,  I like this project and know how it work
When talk about persist schedules and restore schedules , i have an idea inspired by node-schedule(https://github.com/node-schedule/node-schedule).

Current Flow：
buildJob---> saveJob & setKeyExpire --->onJobKeyExpiry ----> handle & (if recur then rebuild and resetKey)
My Idea: 
buildJob---> saveJob & pushToInvocationList ---> redis blpop ----> handle & (if recur then repush )

So, when shutdown, all invocation & job is persist , and when restart or add worker , we can restore schedules without do extra work

Hope Advice from you

**Comment by lykmapipo** [comment]
Thanks. Can we work on this.

**Comment by sunkuo** [comment]
Sure , I will make it and submit a PR

**Comment by lykmapipo** [comment]
Appreciated.

**Comment by lykmapipo** [comment]
Implemented. Will be on v0.7.0 release
