### ISSUE TITLE
Already-scheduled validation

### ISSUE THREAD

**Issue by keenondrums** [lykmapipo/kue-scheduler#7]
I suggest to perform some kind of already-scheduled and already-delayed optional validation upon invoking every and schedule functions. Currently I wrap every function call with the wrappers I describe below, it would be nice use something like it internally in the lib.

```js 
module.exports.checkJobAlreadyScheduled = function *(name) {
    var regExp = new RegExp(name);
    var iteratee = 0;
    var keys = [];
    var res;
    do {
        res = yield redis.scanAsync(iteratee, 'MATCH', kuePrefix + ':scheduler:data:*');
        iteratee = parseInt(res[0]);
        if (res[1].length) {
            keys.push(res[1]);
        }
    }
    while (iteratee != 0);

    keys = _.flatten(keys);
    keys = yield _.map(keys, function (key) {
        return redis.getAsync(key);
    });

    return _.reduce(keys, function (total, val) {
        return total || (val.match(regExp) !== null);
    }, false);
};

module.exports.checkJobAlreadyDelayed = function *(name) {
    var iteratee = 0;
    var keys = [];
    var res;

    var ids = yield redis.zrangeAsync(kuePrefix + ':jobs:delayed', 0, -1);

    keys = _.map(ids, function (id) {
        return kuePrefix + ':job:' + id;
    });
    keys = yield _.map(keys, function (key) {
        return redis.hgetAsync(key, 'type');
    });

    return _.reduce(keys, function (total, val) {
        return total || (val === name);
    }, false);
};
```

**Comment by lykmapipo** [comment]
@keenondrums 

Correct me if am wrong. This will help us to have a single job scheduled.

**Comment by lykmapipo** [comment]
@keenondrums 

It sound as a good idea/feature but am trying to grasp its use case.
Help me on that.

**Comment by keenondrums** [comment]
>> Correct me if am wrong. This will help us to have a single job scheduled.
That's correct.

>>It sound as a good idea/feature but am trying to grasp its use case.
Help me on that.

My use case: I use a set of initializers  upon the start of my Express app. One of them is an automatic scheduler for some periodic jobs (like email, counter gatherer and etc). If I have my server restarted, I'll end up with a second periodical job scheduled.

**Comment by lykmapipo** [comment]
@keenondrums 

That is acceptable. Lets work on it. 
Am open for the discuss?.

**Comment by keenondrums** [comment]
I'll make a pull request with a first draft of how I see it tomorrow. OK? I'll be glad to hear from you with any comments on Skype: keenondrums. That works for you?

**Comment by lykmapipo** [comment]
@keenondrums 

I think discussion over this issue will be better than skype. For references and to help others to contribute

**Comment by lykmapipo** [comment]
@keenondrums 

I  have start to implement a `unique` scheduled and reccur jobs.

**Comment by keenondrums** [comment]
I honestly gave it a try but it seems it's easier for me to rewrite your entire lib with generators than solve redis' callback hell with async lol

**Comment by keenondrums** [comment]
My main idea is to pass the third optional parameter
Queue.prototype.schedule = function (when, job, unique) {
    //this refer to kue Queue instance context
    var self = this;

    if (arguments.length < 2) {
        self.emit(
            'schedule error',
            new Error('Invalid number of parameters. See API doc.')
        );
    }

    if (!job.type) {
        self.emit(
            'schedule error',
            new Error('Invalid job type. See API doc.')
        );
    }

    if (unique) {
        if (self._checkJobAlreadyDelayed(job.type)) {
            return;
        }
    }

....

**Comment by keenondrums** [comment]
Queue.prototype.every = function (interval, job, unique) {
    //this refer to kue Queue instance context
    var self = this;

    if (arguments.length < 2) {
        self.emit(
            'schedule error',
            new Error('Invalid number of parameters. See API doc.')
        );
    }

    if (!job.type) {
        self.emit(
            'schedule error',
            new Error('Invalid job type. See API doc.')
        );
    }

    if (unique) {
        if (self._checkJobAlreadyScheduled(job.type)) {
            return;
        }
    }

**Comment by lykmapipo** [comment]
@keenondrums 

Am using the same idea of passing `unique` as last parameter. Still on pseudocodes.
May you share a branch with what you have been up to?. I will appreciate.

**Comment by lykmapipo** [comment]
@keenondrums 

Returning error if number of parameters are less than required will break a backward compatibility.
Best approach is for it be optional parameter.

Also internal `kue-scheduler` using `UUID` to generate unique keys for `reccur jobs`. While leverage `kue delayed jobs` for `schedule` a job.

**Comment by lykmapipo** [comment]
@keenondrums 

What about leveraging [unique-kue](https://github.com/saintmac/unique-kue)

**Comment by keenondrums** [comment]
That guy deletes an old job to ensure that the job is unique. I find it kind of ugly. 
>Returning error if number of parameters are less than required will break a backward compatibility.
Best approach is for it be optional parameter.
Personally, I don't see how it would break it.
You user to check
    arguments.length !== 2
I suggest 
    arguments.length < 2
to let an addition optional parameter pass the validation. Less then 2 is less strict validation than not equal 2. From my point of view, it's ot gonna break backward compatibility. Correct me if I'm wrong.

That's my branch https://github.com/keenondrums/kue-scheduler/tree/uniqueScheduling
but you won't find there much. I wanted to implement async.doWhilst but didnt have time to do it, unfortunatelly

**Comment by lykmapipo** [comment]
@keenondrums 

Take you time to implement it. I will be merging it with what i will have.

Thanks.

**Comment by keenondrums** [comment]
I managed to do it. A pull request created.

**Comment by keenondrums** [comment]
Pull request failed due to "send_command is not in camel case", still i would appreciate if you look into it

**Comment by lykmapipo** [comment]
@keenondrums 

I appreciate. Am on it.
