### ISSUE TITLE
Setting worker:false doesn't stop process.

### ISSUE THREAD

**Issue by richburdon** [lykmapipo/kue-scheduler#80]
I'm creating a simple scheduler client to test my running kue-scheduler.

let queue = kue.createQueue({worker:false});
queue.now(queue.createJob('test', {}));

The job gets processed fine (by the running worker), but I was expecting the client process to just end after enqueuing the job (given that it is not a worker), but it hangs. What's going on?

**Comment by lykmapipo** [comment]
@richburdon Its by design since `kue-scheduler` rely heavily on [kue](https://github.com/Automattic/kue) for all its queue work. kue always keep worker waiting for the next job to process unless you exit/kill the process.
